### ISSUE TITLE
How to obtain the needed .env variable?

### ISSUE THREAD

**Issue by sonicjhon1** [yasinatesim/instagram-media-downloader#2]
As stated in the title, is there any guide on how to obtain:
NEXT_PUBLIC_IG_DEVICE_STRING 
NEXT_PUBLIC_IG_DEVICE_ID 
NEXT_PUBLIC_IG_UUID 
NEXT_PUBLIC_IG_PHONE_ID 
NEXT_PUBLIC_IG_ADID 
NEXT_PUBLIC_IG_BUILD

**Comment by yasinatesim** [comment]
The project uses to [dilame/instagram-private-api](https://github.com/dilame). When using this library, if you want you can use the below code;
```js
ig.state.generateDevice(process.env.IG_USERNAME);
```
Example is [here](https://github.com/dilame/instagram-private-api#examples).

I didn't want use it because, every time I refresh the page it chooses a different device with [generateDevice](https://github.com/dilame/instagram-private-api/blob/623a348343e34058c3a286693740aa3698aed3cc/src/core/state.ts#L245) and Instagram blocked my authenticated user so I didn't use to [generateDevice](https://github.com/dilame/instagram-private-api/blob/623a348343e34058c3a286693740aa3698aed3cc/src/core/state.ts#L245) function and I defined it as contants;

```js
  public generateDevice(seed: string): void {
    const chance = new Chance(seed);
    this.deviceString = chance.pickone(devices);
    const id = chance.string({
      pool: 'abcdef0123456789',
      length: 16,
    });
    this.deviceId = `android-${id}`;
    this.uuid = chance.guid();
    this.phoneId = chance.guid();
    this.adid = chance.guid();
    this.build = chance.pickone(builds);
  }
```
Can you please check [generateDevice](https://github.com/dilame/instagram-private-api/blob/623a348343e34058c3a286693740aa3698aed3cc/src/core/state.ts#L245) function in dilame/private-instagram-api package?
