### ISSUE TITLE
Not working on localhost

### ISSUE THREAD

**Issue by hasankaantan** [yasinatesim/instagram-media-downloader#7]
I applied every step as you have mentioned on readme. My instagram details are correct and generated a device string via instagram developers page.
After yarn start, I can access to main page locally. I enter username and click search button but nothing happens. Is it mandatory to enter .env fileds below? I am really quite new to js or js based frameworks. Any help will be really important to me. Cheers!

# https://github.com/yasinatesim/instagram-fullsize-picture/issues/6#issuecomment-1424191150
NEXT_PUBLIC_ADMIN_PASSWORD='{{your-admin-password}}'

# Your Firebase - Firestore Database info -> https://console.firebase.google.com/
# NEXT_PUBLIC_FIREBASE_PRIVATE_KEY=''
# NEXT_PUBLIC_FIREBASE_PROJECT_ID=''
# NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL=''

# https://www.google.com/recaptcha/admin/create
NEXT_PUBLIC_RECAPTCHA_SECRET_KEY=
NEXT_PUBLIC_RECAPTCHA_SITE_KEY=

NEXT_PUBLIC_IG_USERNAME={{myusername}}

NEXT_PUBLIC_IG_PASSWORD={{mypassword}}

NEXT_PUBLIC_APP_URL=http://localhost:3000

NEXT_PUBLIC_IG_DEVICE_STRING={{my-device-string}}

# https://github.com/dilame/instagram-private-api/blob/623a348343e34058c3a286693740aa3698aed3cc/src/core/state.ts#L245
NEXT_PUBLIC_IG_DEVICE_ID={{YOUR-IG-DEVICE-ID}}

NEXT_PUBLIC_IG_UUID={{IG-UUID}}

NEXT_PUBLIC_IG_PHONE_ID={{IG-PHONE-ID}}

NEXT_PUBLIC_IG_ADID={{IG-ADID}}

NEXT_PUBLIC_IG_BUILD={{IG-BUILD}}

**Comment by yasinatesim** [comment]
Hey @hasankaantan 

First, can you please pull to project `master` branch on your local because I made some changes. 

Yep, you should fill env file fields

Let me explain to you

There is an `encrypt` function in the project, please follow https://github.com/yasinatesim/instagram-fullsize-picture/issues/6#issuecomment-1424191150

```
NEXT_PUBLIC_ADMIN_PASSWORD='{{your-admin-password}}'
```

You need Firebase Firestore project for below fields

```
# Your Firebase - Firestore Database info -> https://console.firebase.google.com/
NEXT_PUBLIC_FIREBASE_PRIVATE_KEY=''
NEXT_PUBLIC_FIREBASE_PROJECT_ID=''
NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL=''
```

You need Google Recaptcha token for below field and you should add *localhost* domain in Google Recaptcha console "Domains" section

```
# https://www.google.com/recaptcha/admin/create
NEXT_PUBLIC_RECAPTCHA_SECRET_KEY=
NEXT_PUBLIC_RECAPTCHA_SITE_KEY=
```

You need an Instagram account and enter your username and password

```
NEXT_PUBLIC_IG_USERNAME={{YOUR-INSTAGRAM-USERNAME}}

NEXT_PUBLIC_IG_PASSWORD={{YOUR-INSTAGRAM-PASSWORD}}
```

You need Instagram device string, please choose one on this link https://github.com/dilame/instagram-private-api/blob/623a348343e34058c3a286693740aa3698aed3cc/src/samples/devices.json


```
NEXT_PUBLIC_IG_DEVICE_STRING={{YOUR-IG_DEVICE_STRING}}
````


The project uses to dilame/instagram-private-api.The library has `generateDevice` function and the function return the below fields. Please run this function in the dilame/instagram-private-api project and enter the below fields

```
# https://github.com/dilame/instagram-private-api/blob/623a348343e34058c3a286693740aa3698aed3cc/src/core/state.ts#L245
NEXT_PUBLIC_IG_DEVICE_ID=
NEXT_PUBLIC_IG_UUID=
NEXT_PUBLIC_IG_PHONE_ID=
NEXT_PUBLIC_IG_ADID=
NEXT_PUBLIC_IG_BUILD=
```

I hope it helps you 😊

**Comment by hasankaantan** [comment]
Hi @yasinatesim!
Thank you for your support. It really helped me to figure out where I was misunderstood.
